project_id = "lgnowiyptxuyhibptqga"

[functions.categorize-expense]
verify_jwt = true

[functions.savings-recommendations]
verify_jwt = true

[functions.check-prices]
verify_jwt = false

[functions.generate-report-insights]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true